### ISSUE TITLE
Some Areas Not Showing Underlying Zoning

### ISSUE THREAD

**Issue by aszymier** [open-city/second-city-zoning#7]
Some areas of the city, like the one near my residence in the Big Oaks neighborhood in Chicago, are not displaying the underlying zoning.
![issue](https://cloud.githubusercontent.com/assets/8311870/3752024/0427a49c-1804-11e4-9226-74b7d0a08f49.jpg)

**Comment by derekeder** [comment]
Fixed with the [new version](https://github.com/open-city/second-city-zoning/pull/8) :smiley: 

http://secondcityzoning.org/#/?address=Big%20Oaks%2C%20Chicago%2C%20IL%2C%20United%20States&id=11099

![screen shot 2015-01-07 at 2 02 59 pm](https://cloud.githubusercontent.com/assets/919583/5652405/f3e7a014-9675-11e4-8891-600ac3d6772e.png)
